### ISSUE TITLE
Dead people can make actions

### ISSUE THREAD

**Issue by Kotwic4** [Kotwic4/secrethitler-client#15]
Dissable dead people to do actions

**Comment by Kotwic4** [comment]
maybe we would like to have special screen for dead people or we want to implement read-only current state of action. What do you think @Ahmore ?

**Comment by Kotwic4** [comment]
waiting for backend changes https://github.com/mkaput/secrethitler-server/issues/23

**Comment by Ahmore** [comment]
I think lets make special screen for deaf people to allow them go away :D

**Comment by Ahmore** [comment]
You know, with Leave room button :D

**Comment by Kotwic4** [comment]
DONE
